-- =====================================================================
-- L+R Studio — collapse post_plans.status to 3 workflow values
-- =====================================================================
-- The original 8-value enum (`not_started`, `wip`, `needs_brand_feedback`,
-- `needs_admin_revision`, `approved`, `scheduled`, `posted`, `delayed`)
-- was more state machine than agency-and-brand actually used in practice.
-- The new model is:
--   * `drafting`     — agency working on it; not ready for brand eyes
--   * `needs_review` — agency submitted; brand should look at it
--   * `approved`     — brand has signed off
--
-- Comments are how the brand says "needs changes" — there's no separate
-- status flip for revisions; the row stays at `needs_review` until brand
-- clicks Approve. Agency can flip Approved → Drafting as a manual reopen.
--
-- Migration plan:
--   1. Drop the existing CHECK constraint
--   2. Remap rows
--   3. Update default
--   4. Add new CHECK constraint
--   5. Trim the touch_post_plan_status_stamps trigger so it stops
--      checking for the gone-`posted` value (still stamps approved_at on
--      first transition into approved).
--
-- The status-log table (post_plan_status_log) keeps every historical
-- transition exactly as it was — old `needs_brand_feedback` /
-- `needs_admin_revision` / `posted` / `scheduled` rows survive in the
-- audit trail. Only the live `post_plans.status` column collapses.
--
-- We don't drop the `posted_at` / `approved_at` columns — both remain.
-- `approved_at` is still useful (when did the brand sign off?).
-- `posted_at` is now write-orphaned but keeps any historical timestamps.

-- 1. Drop the existing CHECK constraint. The constraint name is
--    auto-generated by Postgres; look it up by table+column.
do $$
declare
  cname text;
begin
  select conname into cname
    from pg_constraint
   where conrelid = 'public.post_plans'::regclass
     and contype = 'c'
     and pg_get_constraintdef(oid) ilike '%status%in%';
  if cname is not null then
    execute format('alter table public.post_plans drop constraint %I', cname);
  end if;
end$$;

-- 2. Remap existing rows. Mapping confirmed with the user 2026-05-05:
--    not_started / wip / delayed                 → drafting
--    needs_brand_feedback / needs_admin_revision → needs_review
--    approved / scheduled / posted               → approved
update public.post_plans
   set status = case status
     when 'not_started'          then 'drafting'
     when 'wip'                  then 'drafting'
     when 'delayed'              then 'drafting'
     when 'needs_brand_feedback' then 'needs_review'
     when 'needs_admin_revision' then 'needs_review'
     when 'approved'             then 'approved'
     when 'scheduled'            then 'approved'
     when 'posted'               then 'approved'
     else status
   end;

-- 3. Update column default.
alter table public.post_plans
  alter column status set default 'drafting';

-- 4. Add the new tighter CHECK constraint.
alter table public.post_plans
  add constraint post_plans_status_check
  check (status in ('drafting', 'needs_review', 'approved'));

-- 5. Trim the auto-stamp trigger. Drop the `posted_at` half — `posted`
--    is no longer a valid status, so that branch can never fire.
--    `approved_at` stamping stays.
create or replace function public.touch_post_plan_status_stamps()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (tg_op = 'UPDATE') then
    if new.status = 'approved'
       and old.status is distinct from 'approved'
       and new.approved_at is null then
      new.approved_at := now();
    end if;
  end if;
  return new;
end;
$$;
