-- =====================================================================
-- L+R Studio — Brand proposals: foundation (PR 1 of N)
-- =====================================================================
-- Brand users get write power, mediated through an approval gate. Three
-- proposal kinds: a brand-created plan (the plan row exists in a new
-- `proposed` status), a date change on an existing plan, or a copy
-- change on an existing plan.
--
-- This PR is schema-only. No UI consumes any of this yet — PRs 2-6 wire
-- up the buttons / drag-drop / diff / agency review surface. Shipping
-- the schema first means the table + RLS can settle on prod (and any
-- RLS surprises surface) before client code starts depending on them.
--
-- What this migration does:
--   1. Extends `post_plans.status` check to add `'proposed'`.
--   2. Adds a `kind` column to `conversation_messages` so we can render
--      system-generated lifecycle events ("sent for review", "approved",
--      "proposed a copy change") differently from human DMs. Client
--      RLS for INSERT is tightened to `kind = 'user'` so a malicious
--      client can't impersonate system events; the triggers below run
--      as SECURITY DEFINER and bypass that.
--   3. Creates `plan_proposals` (id, post_plan_id, account_id, kind,
--      payload jsonb, status, note, agency_response, etc.) with RLS.
--   4. Adds three triggers that emit system messages into the brand's
--      conversation thread on (a) post_plans status change,
--      (b) plan_proposals insert, (c) plan_proposals status resolution.
--   5. Registers plan_proposals on the supabase_realtime publication.
--
-- The system-message text is intentionally short and verb-phrased
-- ("sent this for brand review", "proposed a copy change") so the UI
-- can render `<author name> <body>` and it reads naturally regardless
-- of who triggered it. `author_id` falls through to the trigger's
-- `auth.uid()` — null for service-role / cron contexts, which the UI
-- renders as a generic system event.

-- =====================================================================
-- 1. Extend post_plans.status check to include 'proposed'
-- =====================================================================
-- The constraint name was auto-generated by the original 0021 and may
-- have been renamed by 0035 to `post_plans_status_check`. We look it up
-- by definition shape (same trick 0035 used) so this migration is
-- robust to either name.

do $$
declare
  cname text;
begin
  select conname into cname
    from pg_constraint
   where conrelid = 'public.post_plans'::regclass
     and contype  = 'c'
     and pg_get_constraintdef(oid) ilike '%status%in%';
  if cname is not null then
    execute format('alter table public.post_plans drop constraint %I', cname);
  end if;
end$$;

alter table public.post_plans
  add constraint post_plans_status_check
  check (status in ('drafting', 'needs_review', 'approved', 'proposed'));

-- =====================================================================
-- 2. conversation_messages.kind — distinguish user DMs from system events
-- =====================================================================

alter table public.conversation_messages
  add column if not exists kind text not null default 'user'
  check (kind in ('user', 'system'));

create index if not exists conversation_messages_kind_idx
  on public.conversation_messages(conversation_id, kind, created_at desc)
  where kind = 'system';

-- Tighten the client INSERT policy so untrusted clients can never
-- forge a system-kind row. Triggers below run as SECURITY DEFINER and
-- bypass this check.
drop policy if exists conversation_messages_insert on public.conversation_messages;
create policy conversation_messages_insert on public.conversation_messages
  for insert to authenticated
  with check (
    author_id = auth.uid()
    and kind = 'user'
    and conversation_id in (select id from public.conversations)
  );

-- =====================================================================
-- 3. plan_proposals — the new table
-- =====================================================================
-- `payload` shape by kind:
--   new_plan     : { /* mirrors the plan's fields the brand set */ }
--                   (in practice the plan row itself holds these values
--                    while status='proposed'; payload may be empty)
--   date_change  : { "scheduled_at": "<new ISO timestamptz>" }
--   copy_change  : { "copy_variants": { "instagram": "...", ... } }
--
-- `account_id` is denormalized off post_plans for RLS short-circuit
-- (RLS reads should avoid round-tripping to post_plans on every check).
-- An insert trigger enforces that account_id matches the parent plan.

create table public.plan_proposals (
  id              uuid primary key default gen_random_uuid(),
  post_plan_id    uuid not null references public.post_plans(id) on delete cascade,
  account_id      uuid not null references public.accounts(id)   on delete cascade,
  proposed_by     uuid references public.profiles(id)            on delete set null,
  kind            text not null check (kind in ('new_plan', 'date_change', 'copy_change')),
  payload         jsonb not null default '{}'::jsonb,
  status          text not null default 'pending'
                  check (status in ('pending', 'approved', 'rejected')),
  note            text,                 -- brand's optional message at proposal time
  agency_response text,                 -- agency's optional note on accept/reject
  created_at      timestamptz not null default now(),
  resolved_at     timestamptz,
  resolved_by     uuid references public.profiles(id) on delete set null,
  acknowledged_at timestamptz           -- agency clicked through / opened review modal
);

create index plan_proposals_plan_idx
  on public.plan_proposals(post_plan_id, created_at desc);

create index plan_proposals_account_pending_idx
  on public.plan_proposals(account_id, created_at desc)
  where status = 'pending';

-- Enforce account_id == parent plan's account on insert / update.
-- Cheap (one indexed lookup) and keeps the denormalization honest.
create or replace function public.check_plan_proposal_account_match()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  plan_account uuid;
begin
  select account_id into plan_account
    from public.post_plans
   where id = new.post_plan_id;
  if plan_account is null then
    raise exception 'plan_proposal references missing post_plan: %', new.post_plan_id;
  end if;
  if new.account_id is distinct from plan_account then
    raise exception 'plan_proposal.account_id (%) does not match post_plan.account_id (%)',
                    new.account_id, plan_account;
  end if;
  return new;
end;
$$;

create trigger plan_proposals_account_match
  before insert or update of post_plan_id, account_id on public.plan_proposals
  for each row execute function public.check_plan_proposal_account_match();

-- =====================================================================
-- 4. RLS for plan_proposals
-- =====================================================================

alter table public.plan_proposals enable row level security;

-- SELECT: agency staff see everything; brand members see their account's
-- proposals only. Mirrors the post_plans pattern exactly.
create policy plan_proposals_select on public.plan_proposals
  for select to authenticated
  using (
    public.is_agency_user()
    or account_id in (select public.accessible_account_ids())
  );

-- INSERT: any authenticated user with access to the account can create a
-- proposal for themselves (proposed_by = auth.uid()). Both brand AND
-- agency can author proposals — agency rarely will, but having symmetric
-- write permits future flows (e.g. agency-side "what if" date probes).
create policy plan_proposals_insert on public.plan_proposals
  for insert to authenticated
  with check (
    proposed_by = auth.uid()
    and (
      public.is_agency_user()
      or account_id in (select public.accessible_account_ids())
    )
  );

-- UPDATE: agency only. Brand can't withdraw or edit a pending proposal
-- in v1 — if they want different terms, they propose again. Keeps the
-- audit trail clean and the agency review surface predictable.
create policy plan_proposals_update_agency on public.plan_proposals
  for update to authenticated
  using (public.is_agency_user())
  with check (public.is_agency_user());

-- DELETE: agency only. Same reasoning; brand-initiated retraction can
-- come later if there's demand.
create policy plan_proposals_delete_agency on public.plan_proposals
  for delete to authenticated
  using (public.is_agency_user());

-- =====================================================================
-- 5. System-message emitter (shared helper for the 3 triggers below)
-- =====================================================================
-- Inserts one row into the brand's conversation_messages with kind='system'
-- and the plan auto-tagged so it shows up filtered on per-plan views.
-- Runs as SECURITY DEFINER to bypass the kind='user' client INSERT check.
--
-- If the brand has no conversation row yet (shouldn't happen — the
-- accounts_ensure_brand_conversation trigger from 0042 covers new brand
-- accounts), the insert is silently skipped rather than raising.

create or replace function public.emit_plan_system_message(
  p_account_id uuid,
  p_plan_id    uuid,
  p_actor_id   uuid,
  p_body       text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  conv_id uuid;
begin
  select id into conv_id
    from public.conversations
   where account_id = p_account_id;
  if conv_id is null then
    return;
  end if;
  insert into public.conversation_messages
    (conversation_id, author_id, body, tagged_post_plan_id, kind)
  values
    (conv_id, p_actor_id, p_body, p_plan_id, 'system');
end;
$$;

-- =====================================================================
-- 6. Trigger: post_plans status change → system message
-- =====================================================================
-- Fires AFTER UPDATE so the new status is committed. Wired alongside
-- the existing log_post_plan_status_change trigger from 0023 (which
-- writes to post_plan_status_log). Both fire; their work is additive.

create or replace function public.emit_post_plan_status_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  msg text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  -- Verb-phrased so it composes with "<Name> <verb>": e.g.
  --   "Lakshith sent this plan for brand review."
  msg := case
    when old.status = 'proposed'     and new.status = 'drafting'     then 'accepted the proposed plan.'
    when old.status = 'proposed'     and new.status = 'needs_review' then 'accepted and sent the proposed plan for brand review.'
    when old.status = 'drafting'     and new.status = 'needs_review' then 'sent this plan for brand review.'
    when old.status = 'needs_review' and new.status = 'approved'     then 'approved this plan.'
    when old.status = 'needs_review' and new.status = 'drafting'     then 'pulled this plan back to drafting.'
    when old.status = 'approved'     and new.status = 'drafting'     then 'moved this plan back to drafting.'
    when old.status = 'approved'     and new.status = 'needs_review' then 'reopened this plan for brand review.'
    else format('changed status from %s to %s.', old.status, new.status)
  end;

  perform public.emit_plan_system_message(new.account_id, new.id, auth.uid(), msg);
  return new;
end;
$$;

create trigger post_plans_emit_status_message
  after update of status on public.post_plans
  for each row execute function public.emit_post_plan_status_message();

-- =====================================================================
-- 7. Trigger: plan_proposals INSERT → system message
-- =====================================================================

create or replace function public.emit_plan_proposal_created_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  msg text;
begin
  msg := case new.kind
    when 'new_plan'    then 'proposed a new post plan.'
    when 'date_change' then 'proposed a new date for this plan.'
    when 'copy_change' then 'proposed copy changes for this plan.'
    else                    format('created a %s proposal.', new.kind)
  end;
  perform public.emit_plan_system_message(new.account_id, new.post_plan_id, new.proposed_by, msg);
  return new;
end;
$$;

create trigger plan_proposals_emit_created_message
  after insert on public.plan_proposals
  for each row execute function public.emit_plan_proposal_created_message();

-- =====================================================================
-- 8. Trigger: plan_proposals resolution (pending → approved/rejected)
-- =====================================================================
-- Also stamps resolved_at / resolved_by automatically when the status
-- flips. UI doesn't need to set them explicitly.

create or replace function public.emit_plan_proposal_resolved_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  msg text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;
  if old.status <> 'pending' then
    return new;  -- only emit on first resolution
  end if;

  msg := case new.kind
    when 'new_plan'    then case new.status
      when 'approved' then 'accepted the proposed plan.'
      when 'rejected' then 'rejected the proposed plan.'
      else format('marked the proposed plan as %s.', new.status) end
    when 'date_change' then case new.status
      when 'approved' then 'accepted the proposed date change.'
      when 'rejected' then 'rejected the proposed date change.'
      else format('marked the date proposal as %s.', new.status) end
    when 'copy_change' then case new.status
      when 'approved' then 'accepted the proposed copy changes.'
      when 'rejected' then 'rejected the proposed copy changes.'
      else format('marked the copy proposal as %s.', new.status) end
    else format('resolved a %s proposal as %s.', new.kind, new.status)
  end;

  perform public.emit_plan_system_message(new.account_id, new.post_plan_id, auth.uid(), msg);
  return new;
end;
$$;

create trigger plan_proposals_emit_resolved_message
  after update of status on public.plan_proposals
  for each row execute function public.emit_plan_proposal_resolved_message();

-- Auto-stamp resolved_at / resolved_by on status transition.
create or replace function public.stamp_plan_proposal_resolution()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status
     and old.status = 'pending'
     and new.status in ('approved', 'rejected') then
    if new.resolved_at is null then new.resolved_at := now(); end if;
    if new.resolved_by is null then new.resolved_by := auth.uid(); end if;
  end if;
  return new;
end;
$$;

create trigger plan_proposals_stamp_resolution
  before update of status on public.plan_proposals
  for each row execute function public.stamp_plan_proposal_resolution();

-- =====================================================================
-- 9. Realtime
-- =====================================================================

alter publication supabase_realtime add table public.plan_proposals;
